version: "3"
services:
  db:
    container_name: GROW_Postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
    network_mode: "host"

  python:
    container_name: GROW_Python
    build: ./
    depends_on:
      - db
    volumes:
      - .:/app
    network_mode: "host"
